### PR TITLE
Enable toggling stops and/or routes for each transit type on map

### PR DESCRIPTION
**Pull request by mbjackson-capp**
**NOTE TO SELF: DO NOT DELETE BRANCH UPON MERGING**

The layer control in the upper-right will now let you click on or off the stops and/or routes for each transit mode. It only populates the transit types that exist in the city you're looking at, so e.g. you won't see "subway" in Portland or "aerial tram" in Chicago. (one minor bug: it seems to populate a "Commuter rail routes" checkbox for NYC, even though we didn't ingest NYC area commuter lines; it doesn't do anything).

This also sets us up to, when ready, include a toggle for "User-drawn routes" and possibly "User-drawn endpoints," which will let policymakers view feedback alongside existing infrastructure, or by itself. I will add those once #129 unblocks #117.

Screenshots -- here's Portland with just streetcar and commuter rail checked:

Screen Shot 2024-05-20 at 9 38 28 PM

And here's a weirder set, just to show it's doable (bus stops, but commuter rail and aerial tram routes):

Screen Shot 2024-05-20 at 9 39 25 PM

"Bikeshed"-priority-level followup: consider grouping it so stops and routes toggle together for each transit type (so bus stops/routes are one button, subway stops/routes are another, etc.) -- I prefer it this way but there are arguments either way

I've also bounded the minimum and maximum zoom levels to better match what a human resident of a major urban area would need (previously it allowed zooming out to the entire Earth and zooming in closer than a single city block).

### CODE REVIEW

**Comment by jimenasalinas** [comment]
Thanks, Matt! I'm not an expert on maps, but the output looks good to me. In terms of the bug that you're seeing for  NYC, have you taken a look at the underlying data set? It could be that that data for a different mode is labeled as commuter rail

**Review by jimenasalinas — APPROVED** [review]
I would suggest to double check that the labelling for transportation modes in NY looks good, I'm happy to approve besides that

**Comment by mbjackson-capp** [comment]
It looks like there is one component of MTA that has mode number = 2, the Staten Island Railway. It didn't have a color attribute set, so it wasn't displaying. I'll go into Postico to override the `nan` with the actual color. 

A quick check suggests two other routes (NYC buses) have `nan` color as well; before final submission, if we have time, we may want to consider modifying the ingest script to give a default color to routes that don't have one. 
Screen Shot 2024-05-21 at 12 06 18 AM

**Comment by mbjackson-capp** [comment]
It looks like there is one component of MTA that has mode number = 2, the Staten Island Railway. It didn't have a color attribute set, so it wasn't displaying. I'll go into Postico to override the `nan` with the actual color. 

A quick check suggests two other routes (NYC buses) have `nan` color as well; before final submission, if we have time, we may want to consider modifying the ingest script to give a default color to routes that don't have one. 
Screen Shot 2024-05-21 at 12 13 28 AM

**Comment by mbjackson-capp** [comment]
Screen Shot 2024-05-21 at 12 20 18 AM

**Review by meganhmoore — APPROVED** [review]
looks good! maybe we can update the heatmap with similar zoom levels @kdumais111 ?

**Pull request merged**
